version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "instructlab/ui-maintainers"
    allow:
      - dependency-type: "production"
    target-branch: "main"
    labels:
      - "npm dependencies"
      - "frontend"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - typescript-eslint
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - react
          - react-dom
        update-types:
          - "minor"
          - "patch"
      patternfly:
        patterns:
          - "@patternfly/*"
          - patternfly
        update-types:
          - "minor"
          - "patch"
      typescript-libraries:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    reviewers:
      - "instructlab/ui-maintainers"
    target-branch: "main"
    labels:
      - "github-actions"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/pathservice"
    schedule:
      interval: "weekly"
    reviewers:
      - "instructlab/ui-maintainers"
    target-branch: "main"
    labels:
      - "go dependencies"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
    reviewers:
      - "instructlab/ui-maintainers"
    labels:
      - "docker dependencies"
