contact_links:
  - name: â“ Help and Support Slack Channel
    url: https://app.slack.com/client/T06TXCT5SNM
    about: Please ask and answer questions here. ğŸ¥
  - name: â“ Help and Support Discord Channel
    url: https://discord.gg/Fa6tRapUZ2
    about: Please ask and answer questions here. ğŸ¥
