apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-ui
spec:
  secretName: letsencrypt-ui
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  subject:
    organizations:
      - nexodus
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - qa.ui.instructlab.ai
  issuerRef:
    name: letsencrypt-ui
    kind: Issuer
