apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - ../../base

secretGenerator:
- name: ui-config
  envs:
  - .env

patches:
  - target:
      kind: Ingress
      name: ui
    patch: |-
      - op: remove
        path: /spec/tls/0/secretName

  # Override the UI image for Kind deployment
  - target:
      kind: Deployment
      name: ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/instructlab-ui/ui:main # Override this image if you want to use a different UI image
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  # Override the pathservice image for Kind deployment
  - target:
      kind: Deployment
      name: pathservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/instructlab-ui/pathservice:main # Override this image if you want to use a different pathservice image
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

