version: '5.1'

services:
  pathservice:
    image: ghcr.io/instructlab/ui/pathservice:main
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 200M
    ports:
      - "4000:4000"

  ui:
    image: ghcr.io/instructlab/ui/ui:main
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 200M
    ports:
      - "3000:3000"
