apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - ../../base
  - issuer.yaml
  - certificate.yaml

secretGenerator:
- name: ui-config
  envs:
  - .env

patches:
  - target:
      kind: Ingress
      name: ui
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
      - op: replace
        path: /spec/rules/0/host
        value: ui.instructlab.ai
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ui.instructlab.ai

  # Override the UI image for Openshift production deployment
  - target:
      kind: Deployment
      name: ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/instructlab-ui/ui:v1.0.0-beta # Override this image if you want to use a different UI image

  # Override the pathservice image for Openshift production deployment
  - target:
      kind: Deployment
      name: pathservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/instructlab-ui/pathservice:v1.0.0-beta # Override this image if you want to use a different pathservice image

