name: Cherry pick PR into release-1.0 branch

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick_release_1_0:
    runs-on: ubuntu-latest
    name: Cherry pick into release-1.0 branch
    if: ${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick-release-1.0') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cherry pick into release-1.0 branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.10
        with:
          branch: release-1.0
          labels: |
            cherry-pick
          reviewers: |
            instructlab/ui-maintainers
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
